data:
  path_to_data: dataset/
  train_filename: train.tsv
  valid_filename: None
  test_filename: test.tsv
  separator: \t
  text_field_name: title
  label_field_name: is_fake
  path_to_test_pred_scores: predictions.tsv

preprocessing:
  rm_stopwords: False
  lemmatization: False

model:
  model_name: SkolkovoInstitute/russian_toxicity_classifier   # pretrained model from Transformers (Hugging Face)
  max_seq_length: 32                    
  num_classes: 2

training:
  learn_rate: 3e-5                       # learning rate is typically ~1e-5 for transformers
  num_epochs: 5                          # smth around 2-6 epochs is typically fine when finetuning transformers
  batch_size: 32                         # depends on your available GPU memory (in combination with max seq length)
  log_dir: None # logdir                        # for training logs and tensorboard visualizations
  fp16_params: None                      # fp16 support

general:
  seed: 7373  